services:
  player:
    image: rickroll_briefcase-player:local
    build:
      context: ./player
    pull_policy: build

  controller:
    image: rickroll_briefcase-controller:local
    build:
      context: ./controller
      target: runtime
    pull_policy: build
